from enum import Enum


class PolicyDecisionType(str, Enum):
    ALLOW = "ALLOW"
    BLOCK = "BLOCK"
    REQUIRE_CONFIRMATION = "REQUIRE_CONFIRMATION"


class PolicyCheckCode(str, Enum):
    POLICY_NOT_FOUND = "POLICY_NOT_FOUND"
    POLICY_INACTIVE = "POLICY_INACTIVE"
    QUOTE_INVALID = "QUOTE_INVALID"
    CURRENCY_NOT_ALLOWED = "CURRENCY_NOT_ALLOWED"
    CART_ITEM_LIMIT_EXCEEDED = "CART_ITEM_LIMIT_EXCEEDED"
    QUANTITY_LIMIT_EXCEEDED = "QUANTITY_LIMIT_EXCEEDED"
    CATEGORY_NOT_ALLOWED = "CATEGORY_NOT_ALLOWED"
    SKU_BLOCKED = "SKU_BLOCKED"
    SKU_NOT_ALLOWED = "SKU_NOT_ALLOWED"
    AMOUNT_EXCEEDS_LIMIT = "AMOUNT_EXCEEDS_LIMIT"
    REQUIRE_CONFIRMATION = "REQUIRE_CONFIRMATION"
    ALL_CHECKS_PASSED = "ALL_CHECKS_PASSED"
